DELETE  http://localhost:8080/api/productos/2 HTTP/1.1
Content-Type:  application/json

{
    "titulo": "Casco Modificado con PUT",
    "precio": 99999999999,
    "thumbnail" : "CascoModificadoConPut.JPG"
}